import { DailyLog, Project, TimeEntry, Deviation, ProjectChecklist } from '../types';
import { api } from './api';
import { weatherService, WeatherData } from './weatherService';

export const dailyLogService = {
  /**
   * Get all daily logs for a project, sorted newest first
   */
  async getProjectDailyLogs(projectId: string): Promise<DailyLog[]> {
    try {
      const logs = await api.getDocs<DailyLog>('daily_logs');
      return logs
        .filter(l => l.projectId === projectId)
        .sort((a, b) => b.date.localeCompare(a.date));
    } catch (e) {
      console.warn('Error fetching daily logs:', e);
      return [];
    }
  },

  /**
   * Automatically compiles today's daily log by aggregating:
   * 1. Realtime weather from Open-Meteo via weatherService
   * 2. Time entries for today (calculating crew and hours)
   * 3. Completed checklist items for today
   * 4. Deviations registered today
   */
  async compileTodayLog(project: Project, authorName?: string): Promise<DailyLog> {
    const todayStr = new Date().toISOString().split('T')[0];

    // 1. Fetch weather
    let weather: WeatherData;
    try {
      weather = await weatherService.getWeather(project.location || 'Oslo');
    } catch (e) {
      weather = {
        temp: 12,
        condition: 'Opphold',
        windSpeed: 3,
        precipitation: 0,
        description: 'Stabile arbeidsforhold.',
        icon: 'cloud'
      };
    }

    // 2. Fetch today's time entries for this project
    let crewMembers: string[] = [];
    let totalHoursWorked = 0;
    try {
      const allTimeEntries = await api.getDocs<TimeEntry>('time_entries');
      const todayEntries = allTimeEntries.filter(
        t => t.projectId === project.id && (t.date === todayStr || t.date.startsWith(todayStr))
      );
      totalHoursWorked = todayEntries.reduce((sum, t) => sum + (Number(t.hours) || 0), 0);
      crewMembers = Array.from(new Set(todayEntries.map(t => t.userName).filter(Boolean)));
    } catch (e) {
      console.warn('Could not fetch time entries:', e);
    }

    // If no time entries found, fallback to project crew / author
    if (crewMembers.length === 0 && authorName) {
      crewMembers = [authorName];
      totalHoursWorked = 7.5;
    }

    // 3. Fetch completed checklists for today
    let checklistsCompleted: string[] = [];
    try {
      const checklists = await api.getDocs<ProjectChecklist>('project_checklists');
      const projectLists = checklists.filter(c => c.projectId === project.id);
      for (const cl of projectLists) {
        const doneItems = cl.items.filter(i => i.checked || i.status === 'passed');
        if (doneItems.length > 0) {
          checklistsCompleted.push(`${cl.phaseTitle}: ${doneItems.length} punkter kontrollert`);
        }
      }
    } catch (e) {
      console.warn('Could not fetch checklists:', e);
    }

    // 4. Fetch deviations registered today
    let deviationsRegistered: string[] = [];
    try {
      const deviations = await api.getDocs<Deviation>('deviations');
      const todayDevs = deviations.filter(
        d => d.projectId === project.id && (d.createdAt?.startsWith(todayStr) || d.timestamp?.startsWith(todayStr))
      );
      deviationsRegistered = todayDevs.map(d => `${d.title} (${d.severity})`);
    } catch (e) {
      console.warn('Could not fetch deviations:', e);
    }

    // Check if a log already exists for today
    const existingLogs = await this.getProjectDailyLogs(project.id);
    const existingToday = existingLogs.find(l => l.date === todayStr);

    const log: DailyLog = {
      id: existingToday ? existingToday.id : `log_${project.id}_${todayStr}`,
      projectId: project.id,
      date: todayStr,
      temperatureMin: weather.temp - 2,
      temperatureMax: weather.temp + 2,
      windSpeedMax: weather.windSpeed,
      precipitationMm: weather.precipitation,
      weatherDescription: weather.description,
      weatherCondition: weather.condition,
      workAdvice: weather.workAdvice,
      crewCount: crewMembers.length || 1,
      crewMembers: crewMembers.length > 0 ? crewMembers : ['Formann / Tømrer'],
      totalHoursWorked: totalHoursWorked || 7.5,
      completedTasks: checklistsCompleted.length > 0 
        ? checklistsCompleted 
        : ['Ordinær produksjon og fremdrift iht. fremdriftsplan.'],
      checklistsCompleted,
      deviationsRegistered,
      deliveryNotes: 'Byggevarer mottatt og kontrollert iht. mottakskontroll.',
      generalNotes: existingToday?.generalNotes || `Automatisk loggført kl. ${new Date().toLocaleTimeString('no-NO', { hour: '2-digit', minute: '2-digit' })}. Forholdene på plassen var ${weather.condition.toLowerCase()}.`,
      inspectedBy: authorName || 'Byggeleder / Formann',
      signedAt: new Date().toISOString(),
      autoGenerated: true,
      createdAt: existingToday?.createdAt || new Date().toISOString()
    };

    await api.saveDoc('daily_logs', log);
    return log;
  },

  /**
   * Save or manually update a daily log
   */
  async saveDailyLog(log: DailyLog): Promise<DailyLog> {
    return await api.saveDoc('daily_logs', log);
  }
};
